# -*- coding: utf-8 -*-
"""CH3_股市資料蒐集、爬蟲與搭建資料庫_已修正

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IHNAyScoKzWPAVjKqooQytT7SWpO83Vf

# 股市資料蒐集、爬蟲與搭建資料庫

## 資料爬蟲

## 證交所資料爬蟲
1. 進入證交所網址：https://www.twse.com.tw/zh/index.html
2. 使用開發者模式取得請求資料網址

### 1️⃣ 匯入套件
"""

import requests
import pandas as pd
import datetime as dt # 時間套件
from dateutil.relativedelta import relativedelta

"""### 2️⃣ 取得個股日成交資訊"""

# 輸入股票代號
stock_id = '2330'
# 當日時間
date = dt.date.today().strftime("%Y%m%d")
# 取得證交所網站資料
stock_data = requests.get(f'https://www.twse.com.tw/rwd/zh/ \
            afterTrading/STOCK_DAY?date={date}&stockNo={stock_id}')
json_data = stock_data.json()
df = pd.DataFrame(data=json_data['data'],
                  columns=json_data['fields'])
df.tail()

"""### 3️⃣ 取得連續月份資料
以個股本益比為例
"""

# 設定抓取幾個月資料
month_num=3
date_now = dt.datetime.now()

# 建立日期串列
date_list = [(date_now - relativedelta(months=i)).replace(day=1).\
             strftime('%Y%m%d') for i in range(month_num)]

date_list.reverse()
all_df = pd.DataFrame()

# 使用迴圈抓取連續月份資料
for date in date_list:
  url = f'https://www.twse.com.tw/rwd/zh/afterTrading/\
      BWIBBU?date={date}&stockNo={stock_id}'
  try:
    json_data = requests.get(url).json()
    df = pd.DataFrame(data=json_data['data'],
                  columns=json_data['fields'])
    all_df = pd.concat([all_df, df], ignore_index=True)
  except Exception as e:
    print(f"無法取得{date}的資料, 可能資料量不足.")

all_df.head()

"""## 用 BeautifulSoup4 取得 Yahoo 股市資料

###4️⃣ 匯入套件
"""

from datetime import datetime
from bs4 import BeautifulSoup
import time

"""###  5️⃣ 取得當日股價"""

def yahoo_stock(stock_id):
    url = f'https://tw.stock.yahoo.com/quote/{stock_id}.TW'

    # 設定 Headers，模仿瀏覽器行為
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}

    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')

    # 定位主區塊(防呆機制)
    info_section = soup.find('section', {'id': 'qsp-overview-realtime-info'})
    if not info_section:
        return "找不到區塊"

    # 1. 修正日期抓取：改抓標籤內的文字 (如 11:48 或 2024/03/10)
    time_element = info_section.find('time')
    trade_time = time_element.text if time_element else "未知"

    # 2. 精準抓取數據：確保標題與數值一對一
    fields = []
    datas = []
    items = info_section.find_all('li')

    for item in items:
        # 抓取該 li 下的所有 span
        spans = item.find_all('span')
        if len(spans) >= 2:
            # 排除掉空值，確保左右對齊
            field_name = spans[0].text.strip()
            data_value = spans[1].text.strip()
            if field_name:
                fields.append(field_name)
                datas.append(data_value)

    # 3. 建立 DataFrame 並插入日期與股號
    df = pd.DataFrame([datas], columns=fields)
    df.insert(0, '日期', trade_time)
    df.insert(1, '股號', stock_id)

    return df

# --- 執行測試 ---
# 這裡直接呼叫，不要加 print()，就會出現你要的精美表格格式
yahoo_stock(stock_id)

"""### 6️⃣ 取得季報表資訊

"""

# 函式可用於奇摩財報
def url_find(url):
    # 設定 Headers，模仿瀏覽器行為
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    }

    # 提取網址最後一部分，例如 'income-statement'
    words = url.split('/')
    k = words[-1]

    # 使用 requests 取得網頁內容
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        print(f"連線失敗，狀態碼：{response.status_code}")
        return None

    html = response.content
    soup = BeautifulSoup(html, 'html.parser')

    # 1. 找到表格的主區塊
    # Yahoo 的財報 ID 結構為 'qsp-income-statement-table'
    section_id = f'qsp-{k}-table'
    table_soup = soup.find('section', {'id': section_id})

    if not table_soup:
        print(f"錯誤：找不到 ID 為 {section_id} 的表格區塊。")
        return None

    # 2. 找到表格的表頭 (年份/季度)
    table_fields = table_soup.find('div', class_='table-header')
    if not table_fields:
        print("找不到表頭區塊")
        return None
    table_fields_lines = list(table_fields.stripped_strings)

    # 3. 找到每一行的數據 (損益科目)
    data_rows = table_soup.find_all('li', class_='List(n)')

    data = []
    for row in data_rows:
        row_data = list(row.stripped_strings)
        # 確保資料完整才加入
        if row_data:
            data.append(row_data)

    # 4. 建立 DataFrame
    # 檢查資料列與標題長度是否匹配
    df = pd.DataFrame(data, columns=table_fields_lines)
    return df


# 抓損益表
url = f'https://tw.stock.yahoo.com/quote/{stock_id}/income-statement'

# 執行抓取
raw_df = url_find(url)

if raw_df is not None:
    # 轉置資料處理
    df = raw_df.transpose()
    df.columns = df.iloc[0]
    df = df[1:]
    df.insert(0, '年度/季別', df.index)
    df.columns.name = None
    df.reset_index(drop=True, inplace=True)

    # 顯示最後五筆
    # 在 Jupyter/Colab 裡，直接寫 df.tail() 會呈現漂亮的表格
    display(df.tail()) # 或者直接用 df.tail()

"""##使用 selenium 做新聞爬蟲

### 7️⃣ 用 requests 取得股票新聞
"""

# 股票代號
stock_id = "2330"
# 預設表格數據和欄位
field=['股號','日期','標題','內容']
data=[]
# 取得 Json 格式資料
json_data = requests.get(f'https://ess.api.cnyes.com/ess/api/'
                f'v1/news/keyword?q={stock_id}&limit=20&page=1').json()
# 依照格式擷取資料
items=json_data['data']['items']
for item in items:
    # 網址、標題和日期
    news_id = item["newsId"]
    title = item["title"]
    publish_at = item["publishAt"]
    # 使用 UTC 時間格式
    utc_time = datetime.utcfromtimestamp(publish_at)
    formatted_date = utc_time.strftime('%Y-%m-%d')
    # 前往網址擷取內容
    url = requests.get(f'https://news.cnyes.com/'
                       f'news/id/{news_id}').content
    soup = BeautifulSoup(url, 'html.parser')
    p_elements = soup.find_all('p')
    # 提取段落内容
    p=''
    for paragraph in p_elements[4:]:
        p+=paragraph.get_text()
    data.append([stock_id, formatted_date ,title,p])
# 建立表格
df = pd.DataFrame(data,columns=field)
df

"""### 8️⃣  安裝及匯入套件(跳過)"""

!pip install selenium
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')  # 不顯示瀏覽器
chrome_options.add_argument('--no-sandbox')# 以最高權限運行

"""### 9️⃣ 使用 Selenium 取得股票新聞(跳過)"""

import requests
from datetime import datetime
from bs4 import BeautifulSoup

# --- 這是原本第 9 步驟想做的事，但我們用第 7 步驟的方法做 ---

# 股票代號 (從之前的步驟複製，確保此儲存格獨立運行)
stock_id = "2330"
# 預設表格數據和欄位 (從之前的步驟複製，確保此儲存格獨立運行)
field=['股號','日期','標題','內容']

# 1. 取得搜尋資料 (q={stock_id} 就是搜尋關鍵字)
# 我們把 limit 改成 50，讓你一次抓更多，就像 Selenium 捲動頁面一樣
search_url = f'https://ess.api.cnyes.com/ess/api/v1/news/keyword?q={stock_id}&limit=50&page=1'
json_data = requests.get(search_url).json()
items = json_data['data']['items']

data2 = []

# 2. 依照第 7 步驟的邏輯解析資料
for item in items:
    news_id = item["newsId"]
    title = item["title"]
    publish_at = item["publishAt"]

    # 格式化日期為 YYYY/MM/DD (符合你截圖的樣子)
    formatted_date = datetime.fromtimestamp(publish_at).strftime('%Y/%m/%d')

    # 前往網址擷取內容
    url = f'https://news.cnyes.com/news/id/{news_id}'
    try:
        response = requests.get(url, timeout=5)
        soup = BeautifulSoup(response.content, 'html.parser')

        # 抓取內文 (這部分對應你截圖中的「內容」)
        # 抓取所有 p 標籤並合併成一段文字
        p_elements = soup.find_all('p')
        p_text = ""
        for paragraph in p_elements[4:]: # 跳過前 4 段廣告或導覽
            p_text += paragraph.get_text()

        data2.append([stock_id, formatted_date, title, p_text])
    except:
        data2.append([stock_id, formatted_date, title, "內容抓取失敗"])

# 3. 建立表格
df = pd.DataFrame(data2, columns=field)

# 顯示最後幾筆，確認長相
df.tail()

"""```
#把資料存成 csv 可以用以下這段
df.to_csv('/content/news_data.csv' )
```

#3.3 用 Python 套件輕鬆取得股市資料

##使用 yfinance 下載股市資料

### 🔟  安裝及匯入套件
"""

!pip install yfinance
import yfinance as yf

"""### 1️⃣1️⃣  設定股票代碼和起止時間"""

# 指定要下載的股票代碼, 上市為 .TW;上櫃為 .TWO
stock_id = '2330.TW'
# 設定開始與結束時間
end = dt.date.today()
start = end - dt.timedelta(days=360)

"""### 1️⃣2️⃣ 取得每日股價 (開高低收) 資料"""

stock_data = yf.download(stock_id, start=start, auto_adjust=False, multi_level_index=False)
stock_data.tail()

"""```
# 依照資料期間下載
stock_data = yf.download(stock_id, period="3mo")

# 下載不同時間頻率的資料 (1分K)
stock_data = yf.download(stock_id, interval="1m")
```

### 1️⃣3️⃣ 取得多檔股票的資料
"""

stocks = [stock_id, '2303.TW', '2454.TW'] #分別為台積電、聯電和聯發科
stock_data = yf.download(stocks, start=start, end=end)
stock_data.tail()

"""### 1️⃣4️⃣ 取得公司基本資料

"""

stock = yf.Ticker(stock_id)
stock.info # 為字典型態

"""### 1️⃣5️⃣  取得損益表"""

financials = stock.financials
financials.tail()

bs = stock.balance_sheet
bs

"""### 1️⃣6️⃣ 取得法人持股比例
因 yfinance 資料問題，此儲存格暫時無法使用
"""

institutional_holders = stock.institutional_holders
institutional_holders.tail()

"""## 使用 FinMind 下載股市資料

### 1️⃣7️⃣  安裝及匯入套件
"""

!pip install FinMind
from FinMind.data import DataLoader
import getpass

"""### 1️⃣8️⃣  輸入 FinMind API 和帳號密碼"""

token = getpass.getpass("請輸入 FinMind 金鑰：")

"""### 1️⃣9️⃣  建立 FinMind 資料庫物件和登入 FinMind"""

api = DataLoader()
api.login_by_token(api_token=token)

"""### 2️⃣0️⃣ 取得股價資料"""

# 股票代號
stock_id = '2330'
# 資料期間
end = dt.date.today()
start = end - dt.timedelta(days=360)

stock_data =  api.taiwan_stock_daily(
    stock_id=stock_id,
    start_date=start,
    end_date=end)

stock_data.tail()

"""### 2️⃣1️⃣ 取得損益表資料"""

financial_data = api.taiwan_stock_financial_statement(
    stock_id=stock_id,
    start_date=str(start),)

financial_data.tail()

"""### 2️⃣2️⃣ 取得法人買賣資料"""

investors_data = api.taiwan_stock_institutional_investors(
    stock_id=stock_id,
    start_date=str(start),)
investors_data.tail()

"""## 使用 FinLab 下載股市資料
注意！FinLab 目前需付費才能取得最新資料

### 2️⃣3️⃣ 安裝及匯入套件
"""

!pip install finlab
import finlab
from finlab import data

"""### 2️⃣4️⃣ 登入 FinLab"""

token = getpass.getpass("請輸入FinLab金鑰：")
finlab.login(token)

"""### 2️⃣5️⃣ 取得收盤價"""

close = data.get('price:收盤價')
close.tail()

"""### 2️⃣6️⃣ 選擇產業"""

data.set_universe(market='TSE', category='半導體')
close = data.get('price:收盤價')
close.tail()

"""### 2️⃣7️⃣ 取得財報資料"""

df = data.get('financial_statement:每股盈餘')
df.tail()

"""### 2️⃣8️⃣  取得法人資料"""

df = data.get('institutional_investors_trading_summary:投信買賣超股數')
df.tail()

"""#3.4 SQL資料庫

### 2️⃣9️⃣ 匯入套件及連線資料庫
"""

import sqlite3
conn = sqlite3.connect('stock.db')

"""### 3️⃣0️⃣設定資料庫結構"""

cursor = conn.cursor()
cursor.execute('''
CREATE TABLE IF NOT EXISTS 日頻資料 (
    sno INTEGER PRIMARY KEY AUTOINCREMENT,
    Stock_Id TEXT,
    Date DATE,
    Open FLOAT,
    High FLOAT,
    Low FLOAT,
    Close FLOAT,
    Adj_Close FLOAT,
    Volume INTEGER
);
''')
conn.commit()

"""### 3️⃣1️⃣ 傳入資料到資料庫"""

df = yf.download('2330.TW',start='2023-08-01', auto_adjust=False, multi_level_index=False)
df = df.reset_index()
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')
df.rename(columns={"Adj Close": "Adj_Close"}, inplace=True)
df.insert(0,'Stock_id','2330')

df.to_sql('日頻資料',conn,if_exists='append',index=False)

"""### 3️⃣2️⃣ 查詢表格資料"""

def table_info(table_name):
    cursor = conn.cursor()
    cursor.execute(f"PRAGMA table_info({table_name})")
    columns = cursor.fetchall()
    column_names = [column[1] for column in columns]
    print(f"資料庫表 '{table_name}' 的欄位名稱：", column_names)
    all_data = conn.execute(f'SELECT * FROM {table_name}')
    for i in all_data.fetchall():
        print(i)

# 查詢表格資料
table_info("日頻資料")

"""### 3️⃣3️⃣ 新增資料"""

def insert_data(stock_id, start):
  # 下載資料
  df = yf.download(f'{stock_id}.TW',start=start, auto_adjust=False, multi_level_index=False)
  df = df.reset_index()
  df.rename(columns={"Adj Close": "Adj_Close"}, inplace=True)
  df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')
  df.insert(0,'Stock_Id',stock_id)

  # 新增資料表
  df.to_sql('日頻資料',conn,if_exists='append',index=False)

# 新增 2317 資料
insert_data(stock_id=2317, start='2023-08-01')

"""### 3️⃣4️⃣ 從資料庫取得資料"""

query = ("SELECT Stock_id, Date, Close "
         "FROM 日頻資料 "
         "WHERE Date < '2023-08-15' AND Stock_id = '2317'")
df = pd.read_sql(query, conn, parse_dates=['Date'])
df.tail()

"""### 3️⃣5️⃣ 修改並關閉資料庫"""

conn.commit()
conn.close()